spring.application.name=jwt-security

#--DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

#Jpa/hibernate properties
spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

#jwt Confugaration
app.jwt.secret=vKfpYdAO5UT1MXr3Z4l9ySFU3gJ2pzTY54nD+fSGTNw=
app.jwt.expiration=20000
app.jwt.refresh-expiration=86400000

